spring:
  profiles:
    active: ${ENV:dev}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false # 성능 하락 방지

  thymeleaf:
    cache: false  # thymeleaf 캐시 미사용으로 새로고침 시 바로 레이아웃 확인 가능

server:
  port: ${SERVER_PORT:8080}